export const Staff_data = [
  { id: 1, name: "Rohan Mehta", salary: 35000, status: "active", paymentStatus: "paid" },
  { id: 2, name: "Priya Sharma", salary: 28000, status: "active", paymentStatus: "pending" },
  { id: 3, name: "Amit Verma", salary: 22000, status: "inactive", paymentStatus: "paid" },
  { id: 4, name: "Kavita Singh", salary: 15000, status: "active", paymentStatus: "pending" },
  { id: 5, name: "Sandeep Kumar", salary: 40000, status: "active", paymentStatus: "paid" },
  { id: 6, name: "Meenal Patil", salary: 26000, status: "inactive", paymentStatus: "pending" },
  { id: 7, name: "Aditya Joshi", salary: 30000, status: "active", paymentStatus: "paid" },
  { id: 8, name: "Nidhi Rawat", salary: 32000, status: "active", paymentStatus: "pending" },
  { id: 9, name: "Rajesh Gupta", salary: 20000, status: "inactive", paymentStatus: "paid" },
  { id: 10, name: "Sneha Kapoor", salary: 35500, status: "active", paymentStatus: "paid" },
  { id: 11, name: "Vikas Rao", salary: 27000, status: "inactive", paymentStatus: "pending" },
  { id: 12, name: "Anita Shetty", salary: 33000, status: "active", paymentStatus: "paid" },
  { id: 13, name: "Ritu Jain", salary: 21000, status: "active", paymentStatus: "pending" },
  { id: 14, name: "Deepak Chauhan", salary: 30000, status: "active", paymentStatus: "paid" },
  { id: 15, name: "Tanvi Deshmukh", salary: 24000, status: "inactive", paymentStatus: "pending" },
  { id: 16, name: "Mohit Singh", salary: 16000, status: "active", paymentStatus: "paid" },
  { id: 17, name: "Shalini Nair", salary: 28000, status: "active", paymentStatus: "pending" },
  { id: 18, name: "Harish Patel", salary: 38000, status: "active", paymentStatus: "paid" },
  { id: 19, name: "Komal Yadav", salary: 20000, status: "inactive", paymentStatus: "pending" },
  { id: 20, name: "Vinay Tiwari", salary: 18000, status: "active", paymentStatus: "paid" },
  { id: 21, name: "Pooja Bansal", salary: 20500, status: "active", paymentStatus: "pending" },
  { id: 22, name: "Suraj Mhatre", salary: 29000, status: "inactive", paymentStatus: "paid" },
  { id: 23, name: "Garima Arora", salary: 34000, status: "active", paymentStatus: "paid" },
  { id: 24, name: "Lokesh Jain", salary: 41000, status: "active", paymentStatus: "pending" },
  { id: 25, name: "Niharika Shah", salary: 27500, status: "inactive", paymentStatus: "pending" }
];
